from doubleSpellingApplication.OperationSystem.ProcessMonitorInformation.ProcessMonitorInformation import ProcessMonitorInformation

singleton_process_monitor_information = ProcessMonitorInformation()