from doubleSpellingApplication.Stimulation_Operation.StimulationSystem.StimulationProcess.StimulationController import StimulationController


controller_StimulationController = StimulationController()