from doubleSpellingApplication.Stimulation_Operation.StimulationSystem.StimulationUICreator.SchemaStimulationFramesFactory import SchemaStimulationFramesFactory

factory_SchemaStimulationFramesFactory = SchemaStimulationFramesFactory()
